import generator from 'generate-password';
import bcrypt from 'bcrypt';

export const autoGeneratedPassword: string = generator.generate({
  length: 8,
  numbers: true,
  symbols: true,
  uppercase: true,
  lowercase: true,
  strict: true,
});

const saltRounds = 10; // Number of salt rounds to use for hashing

export const hashPassword = async (): Promise<string> => {
  try {
    const salt = await bcrypt.genSalt(saltRounds);
    const hashedPassword = await bcrypt.hash(autoGeneratedPassword, salt);
    return hashedPassword;
  } catch (error) {
    throw new Error('Error hashing password');
  }
};
