import { Request, Response } from 'express';
import { prisma } from '../config/prisma-connection';
import { generateLecturerIdNumber } from '../utilities/id-utility';
import {
  hashPassword,
  autoGeneratePassword,
} from '../utilities/password-utility';
import { sendAccountInvite } from '../utilities/nodemailer-utility';

// funtion to generate lecture information from request body
export const adminGenerateLecturers = async (req: Request, res: Response) => {
  const firstName: string = req.body.firstName;
  const lastName: string = req.body.lastName;
  const email: string = req.body.email;
  const name = `${firstName} ${lastName}`;
  const genPassword = autoGeneratePassword; // autoGenerated password
  const generateID = await generateLecturerIdNumber();
  const lecturerId = `LEC- ${generateID.toString().padStart(5, '0')}`;
  try {
    //next generated number
    const password = await hashPassword(genPassword);

    const newLect = await prisma.user.create({
      data: {
        email: email,
        password,
        loginId: lecturerId,
        role: 'LECTURER',
        lecturer: {
          create: {
            firstName,
            lastName,
            lecturerId: lecturerId,
          },
        },
      },
      include: {
        lecturer: true,
      },
    });

    await sendAccountInvite(name, email, genPassword, 'LECTURER', lecturerId);
    return res.json({
      success: true,
      message: 'Lecturer created successfully',
      data: newLect,
    });
  } catch (error: unknown) {
    res.status(500).json({
      error: error,
    });
  }
};
